fixeded thigs initramfs bringup

diff --git a/_build/lib b/_build/lib
--- a/_build/lib
+++ b/_build/lib
@@ -2,14 +2,13 @@
 
 _exists(){ type $1 2>&1 | grep -iq function; }
 _is_app(){ which $1 >/dev/null 2>&1; }
+_done(){ printf ' [\e[32mdone\e[0m]\n'; }
+_fail(){ printf ' [\e[31mfail\e[0m]\n'; }
 
 _version_increment(){ 
   local v=$(printf "%d" $(cat $BUILD/version 2>/dev/null || printf 0))
   printf "0x%x" "$(( $v + 1 ))" >$BUILD/version
   _version; }
-
-_done(){ printf ' [\e[32mdone\e[0m]\n'; }
-_fail(){ printf ' [\e[31mfail\e[0m]\n'; }
 
 _git_source(){ local name="$1" url="$2"; shift 2
   [ -d "$SOURCES/$name" ] || git clone --depth=1 "$url" "$SOURCES/$name" "$@"; }
@@ -17,7 +16,7 @@ _git_source(){ local name="$1" url="$2"; shift 2
 _arch_hook(){ local hook=$1; shift
   if _exists ${hook}_$DESTARCH
   then ${hook}_$DESTARCH "$@"
-  else ${hook}_default;fi; }
+  else ${hook}_default "$@";fi; }
 
 _arch_file(){
   local t=; [ -n "$1" ] && t=_$1
@@ -27,6 +26,11 @@ _arch_include(){
   local t=; [ -n "$1" ] && t=_$1
   local f=$(find $(find $BUILD -type d -name arch) -type f -name "$DESTARCH$t")
   [ -f "$f" ] && . "$f"; }
+
+__crossinit_default(){ _make(){ make -j2 "$@"; }; }
+
+__exec_default(){
+  PATH=/bin:/sbin:/usr/bin:/usr/sbin chroot $1 /bin/sh -c "$2"; }
 
 _mount_devs(){ test -z "$1" && return 1
   for d in proc sys dev; do
@@ -38,46 +42,6 @@ _ccache(){
   export PATH=/usr/lib/ccache:$PATH
   export CC="ccache gcc"
   export CXX="ccache g++"; }
-
-_require(){ target=$1; shift
-  depend(){ DEPEND=$(echo "$@"|awk -v d="$mod/" -v ORS=' ' -v RS=' ' '
-    BEGIN{IRS=" \n\t"}{gsub(/@/,d);print $1}'); }
-  __hook(){ #echo $n:$1;
-    _exists $1 && $1; }
-  __load(){
-    local DEPEND 
-    unset $target; unset pre$target; unset post$target
-    . $1
-    __hook pre$target;
-    __hook $target
-    [ -n "$1" ] && for d in $DEPEND; do (
-      DEPEND= _require $target $d; )
-    done
-    __hook post$target; }
-  __skel(){
-    if [ "$target" = build ]
-    then 
-      printf "[\e[33m$target\e[0m:\e[36mskel\e[0m:\e[35m$n\e[0m]"
-      for d in $(ls $BUILD/core/skel/)
-      do [ -d $m/$d ] && {
-        printf " $d"
-        cp -r $m/$d $DESTDIR/; }
-    done; _done; fi; }
-  for mod in $@; do
-    [ -z "$mod" ] && continue
-    n=$(basename "$mod")
-    m=$BUILD/$mod
-    if [ -f $m ]; then
-      printf "[\e[33m$target\e[0m:\e[35m$n\e[0m]\n"
-      __load $m
-    elif [ -d $m -a -f $m/$n ]; then
-      __load $m/$n
-      __skel
-    fi
-  done; true; }
-
-_dots(){ c=2; [ -n "$2" ] && c=$2
-  awk 'BEGIN{printf "'"$1"' "}{if(i++%'"$c"'==0)printf "."}END{print " [\x1b[32mdone\x1b[0m]"}'; }
 
 _generic_build(){ (
   test -z "$SYSROOT" && SYSROOT=/
@@ -95,14 +59,14 @@ _generic_build(){ (
       --sysconfdir=$DESTDIR/etc; }
   make -j 2 install; ); }
 
+_exec_destdir(){ _arch_hook __exec "$DESTDIR" "$1"; }
+_exec_debroot(){ _arch_hook __exec "$DEBROOT" "$1"; }
+
 _depend_apt_host(){
   local bin=$1 lib=$2
   test -z "$bin" && return 1
   test -z "$lib" && lib=$1
   which $bin >/dev/null 2>&1 || sudo apt-get install -y --no-install-recommends $lib; }
-
-_exec_build(){   __exec_$DESTARCH "$DESTDIR" "$1";  }
-_exec_debroot(){ __exec_$DESTARCH "$DEBROOT" "$1"; }
 
 __debroot(){
   SCRIPT=testing
@@ -119,13 +83,13 @@ _depend_apt(){
   test -z "$bin" && return 1
   test -z "$lib" && lib=$1
   bin=$(_exec_debroot "which $bin") 2>/dev/null
-  [ -z "$bin" ] && _exec_debroot "apt-get install -y --no-install-recommends $lib"; }
+  [ -n "$bin" ] || _exec_debroot "apt-get install -y --no-install-recommends $lib"; }
 
 _steal_app(){ (
   for a in $@;do
     test -f $DEBROOT/$a   || app=$(_exec_debroot "which $a")
-    test -f $DEBROOT/$app || { printf "\e[31m NOT FOUND: $a\e[0m\n"; return 1; }
-    printf "[\e[33mapp\e[0m:\e[35m$(basename $a)\e[0m] "
+    test -f $DEBROOT/$app || { printf "[\e[31m$a\e[0m]" >&2; return 1; }
+    printf "[\e[33mapp\e[0m:\e[35m$(basename $a)\e[0m]" >&2
     cp $DEBROOT/$app $DESTDIR/bin/
     _steal_libs $app
   done; ); }
@@ -135,8 +99,8 @@ _steal_libs(){ (
   [ -f "$app" ] || app=$(_exec_debroot "which $app") 
   printf '\e[32m+\e[0m'
   for dep in $(_exec_debroot "ldd $app"|awk '{print $1}'); do
-    _steal_lib $dep; done
-  _done; ); }
+    _steal_lib $dep
+  done; ); }
 
 _steal_lib(){ (
   local LIB= dep=$(basename "$1")
@@ -151,11 +115,11 @@ _steal_lib(){ (
   then [ "$dep" = "linux-vdso.so.1" ] || {
     printf "[\e[31m$1:$dep\e[0m]"; }
     return 1
-  elif [ -f $DESTDIR/lib/$(basename $LIB) ]; then printf '\e[33m=\e[0m'
-  else { printf '\e[32m[%s]\e[0m' $dep; cp $LIB $DESTDIR/lib/; }; fi; )
+  elif [ -f $DESTDIR/lib/$(basename $LIB) ]; then printf '\e[33m=\e[0m' >&2
+  else { printf '\e[32m[%s]\e[0m' $dep >&2; cp $LIB $DESTDIR/lib/; }; fi; )
   true; }
 
-__qemu_kvm(){ kvm -cpu host -smp 2 -no-reboot "$@"; }
+__qemu_default(){ kvm -cpu host -smp 2 -no-reboot "$@"; }
 
 _run_kvm(){ # (: test kernel / squashfs-image :)
   x='-nographic'
@@ -171,7 +135,7 @@ _run_kvm(){ # (: test kernel / squashfs-image :)
   [ ":$1:" = ":-x:" ] && { x=; a=; }
 
   # -usb -device usb-host,hostbus=1,hostaddr=5 \
-  $DESTARCH_EMU $x \
+  _arch_hook __qemu $x \
    -boot c \
    -kernel $SOURCES/linux/$KERNEL_IMAGE \
    -hda $SOURCES/gearos.img -hdb $SOURCES/storage.img \
